controller_list:
  name: arm_controller
  action_ns: position_control
  type: position_controllers/JointPositionController
  default: true
  joints:
    joint_base_top
    joint_arm_lower
    joint_arm_upper
    joint_lastlink